### ISSUE TITLE
Problems with color of the lock icon when unlocked

### ISSUE THREAD

**Issue by enselerizer** [iantrich/restriction-card#47] opened 2021-03-17 01:17 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.2.6

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Google Chrome, Win10

**Description of problem:**

`.hidden` class on lock icon (`#overlay`) doesn't appear when custom icon color is set in theme, which prevents the fade animation and color change from working. However, the unlock function works and the icon changes (a custom icon `mdi:lock-open-outline` is set)

**Javascript errors shown in the web inspector (if applicable):**

Nothing

**Additional information:**

**Comment by ildar170975** [comment] 2024-01-16 23:00
@enselerizer 
Please report if the issue is still valid.

**Comment by ildar170975** [comment] 2024-02-10 15:50
No feedback from OP, closing.

**Closed by ildar170975** 2024-02-10 15:50 UTC
Labels: bug, question
