### ISSUE TITLE
Feature request : Different mdi icon after unlocked. 

### ISSUE THREAD

**Issue by horacecar** [iantrich/restriction-card#34] opened 2020-05-26 10:39 UTC
Feature request : Different mdi icon after unlocked. 
Hope we can have lock mdi icon when lock and have unlock icon when unlocked.

**Comment by iantrich** [comment] 2020-06-26 04:29
duplicate of https://github.com/iantrich/restriction-card/issues/11

**Closed by iantrich** 2020-06-26 04:29 UTC
