### ISSUE TITLE
Cant exit from the page where download the restriction card. Conected by iphone

### ISSUE THREAD

**Issue by gorkavedia** [iantrich/restriction-card#103] opened 2023-11-12 12:55 UTC
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment] 2023-11-12 14:01
Consider providing DETAILS - a detailed description of what you tried to do, what you got etc.
The issue is empty and hence will be closed if no details are provided.

**Comment by ildar170975** [comment] 2024-02-10 15:53
No feedback from OP, closing.

**Closed by ildar170975** 2024-02-10 15:53 UTC
Labels: bug, question
