### ISSUE TITLE
Duration parameter without effect

### ISSUE THREAD

**Issue by iridium2001** [iantrich/restriction-card#82] opened 2023-02-26 13:12 UTC
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
1.2.7

**Last working release (if known):**

**Browser and Operating System:**
Edge, Version 110.0.1587.50 (64-Bit)
Home Assistant Core 2023.2.5

**Description of problem:**
 
Duration parameter does not have any effect. Does not cause an error, but seems to be always 5 seconds. Irrespective if set to e.g. 1 or 10 seconds.

type: custom:restriction-card
card:
  show_name: true
  show_icon: true
  type: button
  tap_action:
    action: toggle
  entity: light.licht_eg
restrictions:
  pin:
    code: 1234
duration: 2

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Fusseldieb** [comment] 2023-11-08 14:17
I just tried it, and it seems to work fine.

**Comment by ildar170975** [comment] 2023-11-24 02:05
@iridium2001 
The code you posted is not properly formatted.
Always place a code inside triple "`".
Otherwise it is impossible to analyse. 
You should have checked YOURSELF after posting how the post is displayed.

Regarding the issue.
Please test this code:
```
type: custom:restriction-card
action: hold
duration: 10
card:
  type: entities
  entities:
    - entity: input_boolean.test_boolean
```
It works as intended with a 10 seconds delay.

Please confirm if you still observe the bug, otherwise the issue will be closed.

**Comment by ildar170975** [comment] 2024-02-10 15:48
No feedback from OP for more than 2 months.
Closing.

**Closed by ildar170975** 2024-02-10 15:48 UTC
Labels: bug, question
